server:
  port: 8080

# 应用名称
spring:
  application:
    name: pageHelper
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orange?serverTimezone=UTC
    username: root
    password: 123456789

  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
  helper-dialect: mysql

